spring:
  application:
    name: petsaude-backend

  datasource:
    url: jdbc:sqlite:${SQLITE_DB_PATH:./data/petsaude.db}
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        format_sql: true
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
    org.flywaydb: INFO
    org.hibernate.SQL: WARN

