name: CI
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Build & Test backend
        working-directory: backend
        run: |
          chmod +x mvnw || true
          ./mvnw -q -DskipTests=false verify
