name: CI
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Build & Test backend
        run: |
          if [ -d "backend" ]; then cd backend; fi
          chmod +x mvnw || true
          ./mvnw -q -DskipTests=false verify || mvn -q -DskipTests=false verify

